@module external styles: {..} = "../styles/Home.module.css"

let default = () => {
  <div className={styles["container"]}>
    <Next.Head>
      <title> {React.string("Create Next App")} </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Next.Head>

      <main className={styles["main"]}>
        <h1>
          {React.string("Hello World")}
        </h1>
      </main>
  </div>
}
