let default = () => {
  <div>
    <Next.Head>
      <title> {React.string("Create Next App")} </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Next.Head>

      <main>
        <h1>
          {React.string("Hello World")}
        </h1>
      </main>
  </div>
}
